# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7699cb845fa025915f4894ced344c07039b848fc5f25708663d6566cae28f407acb3c4993839987441d3f8bd3fb76d43d7f2ee40b540043082c7027301f4bc0

test:
  secret_key_base: b66ea381cfd6b4fe0f19e5076242da5fba0e6be6b8429848aa97c8b97f3998fddd741074ea1f5d292db0466850681f39bb3674f0f9b9d442e129e4eb9b08d3c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
